# PerfectOCR/config/master_config.yaml
workflow:
  input_folder: "C:/PerfectOCR/input"
  output_folder: "C:/PerfectOCR/output"
  temp_folder: "C:/PerfectOCR/data/temp"
  log_level: "DEBUG" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  project_root: ".." 
  aggregated_tables_default_name: "all_tables_summary.txt"
  generate_pure_text_file: true # For lineal_coordinator output

# Configuration for JsonOutputHandler, if any specific options are needed in the future
json_output_handler_config: {}

image_preparation:
  quality_assessment_params:
    min_dpi_threshold: 300
    sharpness_threshold_for_assessment: 60.0
    contrast_std_dev_threshold_for_assessment: 20.0
    skew_detection_inform_threshold: 0.1
    severe_skew_degrees_for_assessment: 15.0
  deskew: 
    application_angle_threshold: 0.5
    canny_threshold1: 50
    canny_threshold2: 150
    canny_aperture_size: 3 # Asegúrese que este nombre coincida con lo que usa en .get()
    hough_min_line_length_cap_px: 300
    hough_max_line_gap_px: 20
    hough_threshold: 150
    hough_angle_filter_range_degrees: [-20.0, 20.0] # Asegúrese que es una lista de dos números
    rotation_min_abs_angle_to_apply_degrees: 0.05

  denoise:
    mode: "auto_from_metrics" # "fixed" or "auto_from_metrics"
    fixed_strength: 7       # Strength if mode is "fixed"
    auto_settings:          # Settings if mode is "auto_from_metrics"
      sharpness_thresholds: [50.0, 100.0] # [lower_bound_for_medium, lower_bound_for_high]
      strengths_map:        # Strengths for [low_sharpness, medium_sharpness, high_sharpness]
        - 12                # For sharpness < sharpness_thresholds[0]
        - 7                 # For sharpness_thresholds[0] <= sharpness < sharpness_thresholds[1]
        - 5                 # For sharpness >= sharpness_thresholds[1]

  contrast_enhancement:
    clahe_clip_limit: 2.0
    tile_grid_size_mode: "auto_from_dimensions" # "fixed" or "auto_from_dimensions"
    fixed_tile_grid_size: [8, 8] # [width_tiles, height_tiles] if mode is "fixed"
    auto_tile_settings:
      dimension_thresholds_px: [1000, 2500] # [upper_for_small_grid, upper_for_medium_grid]
      # Grid sizes: [[small_w,small_h], [medium_w,medium_h], [large_w,large_h]]
      grid_sizes:
        - [6, 6]    # If max(img_h,img_w) < dimension_thresholds_px[0]
        - [8, 8]    # If dimension_thresholds_px[0] <= max(img_h,img_w) < dimension_thresholds_px[1]
        - [12, 12]  # Else

  binarization:
    adaptive_c_value: 3
    block_size_mode: "auto_image_size_heuristic" # "fixed" or "auto_image_size_heuristic"
    fixed_block_size: 25 # Block size if mode is "fixed"
    auto_block_size_settings:
      height_thresholds_px: [800, 1500, 2500] 
      #block_sizes: [bs_for_h<T0, bs_for_h<T1, bs_for_h<T2, bs_for_h>=T2] # [upper_for_bs1, upper_for_bs2, upper_for_bs3]
      block_sizes: [11, 17, 25, 35]

spatial_analyzer:
  density_map_window_size: 21 

ocr:
  default_folder_origin: "unknown_mode" # For metadata if not otherwise specified
  default_image_pil_mode: "unknown_mode"  # For metadata if not otherwise specified
  tesseract:
    cmd_path: "C:/Program Files/Tesseract-OCR/tesseract.exe"
    lang: "spa+eng"
    psm: 11
    oem: 1
    preserve_interword_spaces: 1
    confidence_threshold: 0.5
    tessedit_char_whitelist: "0123456789ABCDEFGHIJKLMNÑOPQRSTUVWXYZabcdefghijklmnñopqrstuvwxyz$./%#"
    user_words_path: null # Path to a user words file, or null
    
  paddleocr:
    use_angle_cls: true
    lang: "es"
    det_model_dir: "./models/paddle/det/es"
    rec_model_dir: "./models/paddle/rec/es"
    cls_model_dir: "./models/paddle/cls"
    use_gpu: false
    show_log: false

line_reconstructor_params:
  dynamic_origin_h_threshold: 2800.00
  y_centroid_alignment_ratio_threshold: 0.25
  y_centroid_abs_diff_threshold_px: 15.00

paddle_tesseract_assignment_params:
  min_vertical_overlap_ratio: 0.25
  min_iou_for_assignment: 0.15
  assign_if_tess_centroid_in_paddle_line: true
  paddle_line_x_expansion_factor_for_centroid: 1.5

element_fusion_params:
  iou_threshold_for_fusion: 0.50
  text_similarity_for_strong_match: 0.75
  paddle_confidence_normalization_factor: 85.00
  min_tess_confidence_for_text_priority: 0.50
  paddle_high_confidence_threshold: 90.00

table_extraction_config:
  header_detector_config:
    table_header_keywords_list: [ 
        'CANT', 'CANT.', 'CANTIDAD', 'QTY', 'PZA', 'PZAS', 'PIEZAS', 'UND',
        'DESCRIP', 'DESCRIPCION', 'DESCRIPCIÓN', 'PRODUCTO', 'PRODUCTOS', 'NOMBRE', 'DETALLE', 'CONCEPTO', 'ARTICULO', 'ARTÍCULOS', 'ARTÍCULO',
        'PRECIO', 'P/U', 'P.U.', 'P.UNIT', 'UNITARIO', 'PREC', 'VALOR UNIT', 'VR UNIT', 'PRECIO UNITARIO', 'P UNIT', 'V UNIT', 'V. UNIT',
        'IMPORTE', 'MONTO', 'TOTAL', 'SUBTOTAL', 'VALOR', 'VR TOTAL', 'V TOTAL', 'V. TOTAL',
        'COD', 'CODIGO', 'ID', 'CLAVE', 'ITEM', 'REF', 'REFERENCIA',
        'UNIT', 'UNIDAD', 'MEDIDA', 'U/M', 'UM'
      ]
    table_end_keywords: [ 
        "TOTAL", "SUBTOTAL", "SUMA TOTAL", "OBSERVACIONES", "VALOR TOTAL",
        "GRACIAS POR SU COMPRA", "PAGO CON", "EFECTIVO", "CAMBIO",
        "NO, DE ARTICULOS", "NO. DE ARTICULOS", "TOTAL DE ARTICULOS",
        "FIRMA", "AUTORIZADO POR"
      ]
      
    header_detection_fuzzy_min_ratio: 85.0
    header_min_y_ratio: 0.05 # Min Y position of header relative to page height (0.0-1.0)
    header_max_y_ratio: 0.75 # Max Y position of header relative to page height (0.0-1.0)
    min_header_keywords_in_line: 2
    max_header_keywords_in_line: 5
    max_header_line_gap_factor: 2.50 # Multiplier of avg line height for max gap between header lines
    min_line_confidence_for_header: 70.00 # Min avg confidence of a line to be considered header
    default_line_height_for_gap: 20.00 # Fallback if dynamic line height can't be computed

  column_definer_config:
    dbscan_header_eps: 50.00 # Max distance for DBSCAN clustering of header word centroids
    dbscan_header_min_samples: 1

  row_definer_config:
    row_cluster_distance_threshold_factor: 1.00 # Multiplier of avg word height for row clustering
    default_row_height_fallback: 20.00

  cell_assigner_config:
    cell_cosine_strong_threshold: 0.80 # Min cosine similarity for strong cell assignment
    fallback_cell_iou_threshold: 0.05  # Min IoU for fallback spatial assignment

  spatial_validator_worker_config:
    min_word_density_score_for_consideration: 0.1

  cell_content_analyzer_worker_config:
    example_param: "value_for_cell_analyzer"

  spatial_table_end_detection: 
    density_drop_threshold_ratio: 0.15 # Ratio of density drop to confirm table end
    min_low_density_rows_to_confirm_end: 10
    smoothing_window_size: 5
    ignore_bottom_page_ratio: 0.05 # Percentage of page bottom to ignore for spatial end detection

  data_filter_config:
    min_line_avg_confidence_for_table: 70.0
    min_word_confidence_for_table: 60.0
    min_word_density_score_for_table: 0.0 
    filter_short_non_alphanum_lines: true
    short_line_max_chars_for_filter: 5
    noise_line_max_aspect_ratio: 25.0
    noise_line_min_aspect_ratio: 0.04
    noise_line_min_words_for_extreme_aspect_ratio: 2
    noise_line_min_conf_for_extreme_aspect_ratio: 50.0

  row_validation_config: 
    min_words_in_data_row: 1
    min_alphanumeric_chars_in_data_row: 1

  cell_postprocessing_rules_config:
    quantity_column_keywords: ['CANT', 'CANT.', 'CANTIDAD', 'QTY', 'PZA', 'PZAS', 'PIEZAS', 'UND']
    value_column_keywords: ['PRECIO', 'P/U', 'P.U.', 'P.UNIT', 'UNITARIO', 'PREC', 'VALOR UNIT', 'VR UNIT', 'PRECIO UNITARIO', 'P UNIT', 'V UNIT', 'V. TOTAL', 'V.UNIT', 'IMPORTE', 'MONTO', 'TOTAL', 'SUBTOTAL', 'VALOR', 'VR TOTAL']
    currency_symbols: ['$', '€']

postprocessing:
  text_correction:
    enabled: false
    vocab_path: "data/dictionaries/es_MX.txt"
    min_confidence_spell: 85.0
    # For common_errors and contextual_correction, lambdas are hard to define in YAML.
    # Python code will implement the lambda logic, YAML can enable/disable them or provide simple string patterns.
    apply_common_error_correction_rules_defined_in_code: true # Enable/disable hardcoded common error rules
    apply_contextual_correction_rules_defined_in_code: false # Enable/disable hardcoded contextual rules
    # Example of how simple rules could be defined if needed, but complex ones stay in code:
    # simple_common_errors:
    #   - pattern: "erron"
    #     replacement: "error"
    # contextual_rules_enabled: true # To enable/disable this step
    # contextual_correction_rules:
    #    - pattern: '\b(cliente|proveedor)\b'
    #      expected_context_keywords: ['nombre', 'dirección', 'teléfono']
    #      flags: "IGNORECASE"

  text_formatting:
    format_dates: false
    normalize_numbers: false
    max_line_length_for_preserve_breaks: 80
    # Date patterns are complex for pure YAML; Python can store them and YAML can enable/disable categories
    apply_date_normalization_rules_defined_in_code: true
    # month_names_map: # For date normalization if lambda_month_name_to_num_date is used
    #   enero: '01'
    #   # ...
    #   diciembre: '12'
    #   default_month_num: '00'