# PerfectOCR/config/master_config.yaml
workflow:
  input_folder: "C:/PerfectOCR/input"
  output_folder: "C:/PerfectOCR/output"
  temp_folder: "C:/PerfectOCR/data/temp"
  log_level: "DEBUG" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  project_root: ".." 
  aggregated_tables_default_name: "all_tables_summary.txt"
  generate_pure_text_file: true # For lineal_coordinator output

# Configuration for JsonOutputHandler, if any specific options are needed in the future
json_output_handler_config: {}

image_preparation:
  quality_assessment_rules:
    deskew:
      min_angle_for_correction: 0.1
      canny_thresholds: [50, 150]
      hough_threshold: 150
      hough_min_line_length_cap_px: 300
      hough_max_line_gap_px: 20
      hough_angle_filter_range_degrees: [-20.0, 20.0]
    # REGLAS DIFERENCIADAS: Cada motor tiene su propio conjunto de reglas.
    tesseract:
      denoise:
        sharpness_thresholds: [60.0, 120.0]
        strengths_map: [7, 5, 3] # Menos agresivo para Tesseract
      contrast_enhancement:
        clahe_clip_limit: 1.2
        dimension_thresholds_px: [1000, 2500]
        grid_sizes_map: [[8, 8], [10, 10], [12, 12]]
      binarization:
        adaptive_c_value: 7
        height_thresholds_px: [800, 1500, 2500]
        block_sizes_map: [31, 41, 51, 61] # Bloques más grandes para Tesseract

    paddleocr:
      denoise:
        sharpness_thresholds: [50.0, 100.0]
        strengths_map: [12, 7, 5] # Más agresivo para Paddle
      contrast_enhancement:
        clahe_clip_limit: 2.0
        dimension_thresholds_px: [1000, 2500]
        grid_sizes_map: [[6, 6], [8, 8], [10, 10]]
      binarization:
        adaptive_c_value: 7
        height_thresholds_px: [800, 1500, 2500]
        block_sizes_map: [21, 25, 35, 41]
        
spatial_analyzer:
  density_map_window_size: 21 

ocr:
  default_folder_origin: "unknown_mode" # For metadata if not otherwise specified
  default_image_pil_mode: "unknown_mode"  # For metadata if not otherwise specified
  tesseract:
    cmd_path: "C:/Program Files/Tesseract-OCR/tesseract.exe"
    lang: "spa+eng"
    psm: 4  # Columnas de texto (mejor para recibos/facturas)
    oem: 3  # Default auto-switch (activa LSTM)
    dpi: 300  # DPI específico para mejor reconocimiento
    preserve_interword_spaces: 1
    confidence_threshold: 25.0  # Umbral más bajo para capturar más palabras
    tessedit_char_whitelist: ""  # Sin filtros para permitir todos los caracteres
    user_words_path: null # Path to a user words file, or null
    
  paddleocr:
    use_angle_cls: true
    lang: "es"
    det_model_dir: "./models/paddle/det/es"
    rec_model_dir: "./models/paddle/rec/es"
    cls_model_dir: "./models/paddle/cls"
    use_gpu: false
    show_log: false

line_reconstructor_params:
  dynamic_origin_h_threshold: 2800.00
  y_centroid_alignment_ratio_threshold: 0.25
  y_centroid_abs_diff_threshold_px: 15.00

element_fusion_params:
  iou_threshold_for_fusion: 0.50
  text_similarity_for_strong_match: 0.75
  paddle_confidence_normalization_factor: 85.00
  min_tess_confidence_for_text_priority: 0.50
  paddle_high_confidence_threshold: 90.00

paddle_tesseract_assignment_params:
  min_vertical_overlap_ratio: 0.25
  min_iou_for_assignment: 0.15
  assign_if_tess_centroid_in_paddle_line: true
  paddle_line_x_expansion_factor_for_centroid: 1.5


table_extraction_config:
  header_detector_config:
    table_header_keywords_list: [ 
        'CANT', 'CANT.', 'CANTIDAD', 'QTY', 'PZA', 'PZAS', 'PIEZAS', 'UND',
        'DESCRIP', 'DESCRIPCION', 'DESCRIPCIÓN', 'PRODUCTO', 'PRODUCTOS', 'NOMBRE', 'DETALLE', 'CONCEPTO', 'ARTICULO', 'ARTÍCULOS', 'ARTÍCULO',
        'PRECIO', 'P/U', 'P.U.', 'P.UNIT', 'UNITARIO', 'PREC', 'VALOR UNIT', 'VR UNIT', 'PRECIO UNITARIO', 'P UNIT', 'V UNIT', 'V. UNIT',
        'IMPORTE', 'MONTO', 'TOTAL', 'SUBTOTAL', 'VALOR', 'VR TOTAL', 'V TOTAL', 'V. TOTAL',
        'COD', 'CODIGO', 'ID', 'CLAVE', 'ITEM', 'REF', 'REFERENCIA',
        'UNIT', 'UNIDAD', 'MEDIDA', 'U/M', 'UM'
      ]
    table_end_keywords: [ 
        "TOTAL", "SUBTOTAL", "SUMA TOTAL", "OBSERVACIONES", "VALOR TOTAL",
        "GRACIAS POR SU COMPRA", "PAGO CON", "EFECTIVO", "CAMBIO",
        "NO, DE ARTICULOS", "NO. DE ARTICULOS", "TOTAL DE ARTICULOS",
        "FIRMA", "AUTORIZADO POR"
      ]
      
    header_detection_fuzzy_min_ratio: 85.0
    header_min_y_ratio: 0.05 # Min Y position of header relative to page height (0.0-1.0)
    header_max_y_ratio: 0.75 # Max Y position of header relative to page height (0.0-1.0)
    min_header_keywords_in_line: 2
    max_header_keywords_in_line: 5
    max_header_line_gap_factor: 2.50 # Multiplier of avg line height for max gap between header lines
    min_line_confidence_for_header: 70.00 # Min avg confidence of a line to be considered header
    default_line_height_for_gap: 20.00 # Fallback if dynamic line height can't be computed

  column_definer_config:
    dbscan_header_eps: 50.00 # Max distance for DBSCAN clustering of header word centroids
    dbscan_header_min_samples: 1

  row_definer_config:
    row_cluster_distance_threshold_factor: 1.00 # Multiplier of avg word height for row clustering
    default_row_height_fallback: 20.00

  cell_assigner_config:
    cell_cosine_strong_threshold: 0.80 # Min cosine similarity for strong cell assignment
    fallback_cell_iou_threshold: 0.05  # Min IoU for fallback spatial assignment

  spatial_validator_worker_config:
    min_word_density_score_for_consideration: 0.1

  cell_content_analyzer_worker_config:
    example_param: "value_for_cell_analyzer"

  spatial_table_end_detection: 
    density_drop_threshold_ratio: 0.15 # Ratio of density drop to confirm table end
    min_low_density_rows_to_confirm_end: 10
    smoothing_window_size: 5
    ignore_bottom_page_ratio: 0.05 # Percentage of page bottom to ignore for spatial end detection

  data_filter_config:
    min_line_avg_confidence_for_table: 70.0
    min_word_confidence_for_table: 60.0
    min_word_density_score_for_table: 0.0 
    filter_short_non_alphanum_lines: true
    short_line_max_chars_for_filter: 5
    noise_line_max_aspect_ratio: 25.0
    noise_line_min_aspect_ratio: 0.04
    noise_line_min_words_for_extreme_aspect_ratio: 2
    noise_line_min_conf_for_extreme_aspect_ratio: 50.0

  row_validation_config: 
    min_words_in_data_row: 1
    min_alphanumeric_chars_in_data_row: 1

  cell_postprocessing_rules_config:
    quantity_column_keywords: ['CANT', 'CANT.', 'CANTIDAD', 'QTY', 'PZA', 'PZAS', 'PIEZAS', 'UND']
    value_column_keywords: ['PRECIO', 'P/U', 'P.U.', 'P.UNIT', 'UNITARIO', 'PREC', 'VALOR UNIT', 'VR UNIT', 'PRECIO UNITARIO', 'P UNIT', 'V UNIT', 'V. TOTAL', 'V.UNIT', 'IMPORTE', 'MONTO', 'TOTAL', 'SUBTOTAL', 'VALOR', 'VR TOTAL']
    currency_symbols: ['$', '€']

postprocessing:
  text_correction:
    enabled: false
    vocab_path: "data/dictionaries/es_MX.txt"
    min_confidence_spell: 85.0
    # For common_errors and contextual_correction, lambdas are hard to define in YAML.
    # Python code will implement the lambda logic, YAML can enable/disable them or provide simple string patterns.
    apply_common_error_correction_rules_defined_in_code: true # Enable/disable hardcoded common error rules
    apply_contextual_correction_rules_defined_in_code: false # Enable/disable hardcoded contextual rules
    # Example of how simple rules could be defined if needed, but complex ones stay in code:
    # simple_common_errors:
    #   - pattern: "erron"
    #     replacement: "error"
    # contextual_rules_enabled: true # To enable/disable this step
    # contextual_correction_rules:
    #    - pattern: '\b(cliente|proveedor)\b'
    #      expected_context_keywords: ['nombre', 'dirección', 'teléfono']
    #      flags: "IGNORECASE"

  text_formatting:
    format_dates: false
    normalize_numbers: false
    max_line_length_for_preserve_breaks: 80
    # Date patterns are complex for pure YAML; Python can store them and YAML can enable/disable categories
    apply_date_normalization_rules_defined_in_code: true
    # month_names_map: # For date normalization if lambda_month_name_to_num_date is used
    #   enero: '01'
    #   # ...
    #   diciembre: '12'
    #   default_month_num: '00'